### ISSUE TITLE
Connpassのイベントを作る

### ISSUE THREAD

**Issue by mk2** [fukuirb/meetup#1]
- [x] イベントページのdraft作成 at compass (@mk2 )
- [x] イベントページの公開

---

イベントの内容

- Ruby Kaigi 2023の感想戦
- 開催はオンライン

**Comment by taketo1113** [comment]
## 第0回準備ミーティングログ
### agenda
- 第0回開催概要決め (Must)
- fukui.rb 概要決め&作文 (できれば)
- イベントページ作成 (できれば)

### 第0回開催概要決め
- 日時: 2023/5/20(Sat) 14:00 - 17:00
- 形式: オンライン
  - ツール未定
- 内容
  - fukui.rb の紹介
  - Ruby Kaigi 2023の感想戦
    - おもしろかった/興味のあるセッションの紹介
    - 一緒にアーカイブを見る
    - (雑談)
  - fukui.rb 第1回予定紹介
    - 7/22開催予定
    - オフライン
- 備考
  - Ruby Kaigi 2023 みてない人歓迎
  - 出入り自由

- ツール
  - zoom!? (永和さん提供できるかも。協賛の文言を追加が必要)

### fukui.rb 概要決め
- 福井県および周辺地域在住あるいはRubyに興味のあるすべての人を対象にした地域Rubyコミュニティ
- Rubyを普段使っていない人 / 初心者 / 福井県外の人歓迎
- 基本的にもくもく会、たまにLT会を予定

- 参考: kanazawa.rb
  - https://meetup.kzrb.org/about/

### ロゴ
- 作りたい
  - 第1回までにあるといいな
  - connpass は仮のロゴを使っている
  - https://fukuirb.connpass.com/

- キーワード
  - 恐竜
  - カニ
  - 越野ルビー

- Ruby公式ロゴ ライセンス
  - https://www.ruby.or.jp/ja/about/logo.html
  - > プログラミング言語Rubyに関連する文脈で誰でも自由に利用できます

**Comment by taketo1113** [comment]
公開済み 🎉 
https://fukuirb.connpass.com/event/281866/
